// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetScreenShotPaths() {
  return window['go']['main']['App']['GetScreenShotPaths']();
}

export function Logging(arg1) {
  return window['go']['main']['App']['Logging'](arg1);
}

export function SaveSSPath(arg1) {
  return window['go']['main']['App']['SaveSSPath'](arg1);
}
