// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePhishData(arg1:string):Promise<void>;

export function GetScreenShotPaths():Promise<Array<string>>;

export function Logging(arg1:string):Promise<void>;

export function SaveSSPath(arg1:string):Promise<string>;
